apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: mysqldump
spec:
  schedule: 0 4 * * *
  jobTemplate:
    spec:
      template:
        spec:
          nodeSelector:
            role: mysqldump
          containers:
          - name: mysqldump
            image: e0steven/kubernetes-mysqldump-fuse-cron
            securityContext:
              privileged: true
              capabilities:
                add:
                  - SYS_ADMIN
            lifecycle:
              postStart:
                exec:
                  command: ["gcsfuse", "-o", "nonempty", "your-bucket-name", "/mysqldump"]
              preStop:
                exec:
                  command: ["fusermount", "-u", "/mysqldump"]
            env:
              - name: ALL_DATABASES
                valueFrom:
                  configMapKeyRef:
                    name: mysqldump
                    key: all_databases
              - name: DB_HOST
                valueFrom:
                  configMapKeyRef:
                    name: mysqldump
                    key: dbhost
              - name: DB_USER
                valueFrom:
                  secretKeyRef:
                    name: mysqldump
                    key: dbuser
              - name: DB_PASS
                valueFrom:
                  secretKeyRef:
                    name: mysqldump
                    key: dbpass
            imagePullPolicy: Always
          restartPolicy: OnFailure
